### ISSUE TITLE
(firefox) org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session.

### ISSUE THREAD

**Issue by Komaleeswar** [testvagrant/AppiumDemo#7]
1554126801219	mozrunner::runner	INFO	Running command: "C:\\Program Files (x86)\\Mozilla Firefox\\firefox.exe" "-marionette" "-foreground" "-no-remote" "-profile" "C:\\Users\\KPENDU~1.ORA\\AppData\\Local\\Temp\\rust_mozprofile.qQaIiX4JAaFt"
1554126804285	Marionette	INFO	Listening on port 60755
Exception in thread "main" org.openqa.selenium.SessionNotCreatedException: Unable to create new remote session. desired capabilities = Capabilities [{marionette=true, browserName=firefox, moz:firefoxOptions=org.openqa.selenium.firefox.FirefoxOptions@42d8062c, version=, platform=ANY, firefox_profile=org.openqa.selenium.firefox.FirefoxProfile@6043cd28}], required capabilities = Capabilities [{}]
Build info: version: '3.2.0', revision: '8c03df6', time: '2017-03-02 09:34:51 -0800'
System info: host: 'KPENDURT-LAP', ip: '10.191.227.106', os.name: 'Windows 10', os.arch: 'amd64', os.version: '10.0', java.version: '1.8.0_201'
Driver info: driver.version: FirefoxDriver
	at org.openqa.selenium.remote.ProtocolHandshake.createSession(ProtocolHandshake.java:91)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:141)
	at org.openqa.selenium.remote.service.DriverCommandExecutor.execute(DriverCommandExecutor.java:82)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:604)
	at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:244)
	at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:293)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:272)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:267)
	at org.openqa.selenium.firefox.FirefoxDriver.<init>(FirefoxDriver.java:130)
	at firstTest.FirstTestCase.main(FirstTestCase.java:17)

**Comment by Komaleeswar** [comment]
Guys, Please help me in resolving this issue
